import {
  Code,
  Briefcase,
  Palette,
  GraduationCap,
  Star,
  Heart,
  BookOpen,
  DollarSign,
  TrendingUp,
  Scale,
  Settings,
  Sparkles,
  Wrench,
  Users,
  Utensils,
  Home,
} from "lucide-react";

export interface ProfessionCategory {
  id: string;
  name: string;
  description: string;
  icon: any;
  color: string;
  gradientFrom: string;
  gradientTo: string;
  templateIds: string[];
  isAll?: boolean; // Special flag for the "All" category
}

export const professionCategories: ProfessionCategory[] = [
  {
    id: "all",
    name: "All Templates",
    description: "Browse all our professionally designed resume templates across all categories",
    icon: Sparkles,
    color: "#6366f1",
    gradientFrom: "#6366f1",
    gradientTo: "#8b5cf6",
    isAll: true,
    templateIds: [
      "ai-engineer",
      "api-doc",
      "aws-cloud-engineer",
      "aws-solutions-architect",
      "abstract-version-designer",
      "academic-achiever",
      "academic-advisor",
      "academic-educator",
      "accessibility-designer",
      "accessibility-ux",
      "account-manager-enterprise",
      "accounting-executive",
      "accounting-pro",
      "achiever-fresher",
      "adobe-portfolio-designer",
      "adobexd-designer",
      "aerospace-engineer",
      "aesthetic-creative",
      "affiliate-marketing-manager",
      "agile-project-lead",
      "agile-scrum",
      "agileflow-developer",
      "algo-engineer",
      "amber-executive",
      "analyst",
      "angular-modern-universal",
      "angular-specialist",
      "animation-artist",
      "ansible-automation",
      "apigateway-architect",
      "architect-registered",
      "art-director-modern",
      "art-director-pro",
      "art-station-artist",
      "artisan-designer",
      "artistic-bold",
      "artistic-grid",
      "artistic-horizon",
      "artistic-momentum",
      "artistic-vision",
      "artstation-pro",
      "ascend-graduate",
      "aspire-graduate",
      "asymmetric-creative",
      "asymmetric-layout-universal",
      "atlas-executive",
      "attorney-professional",
      "audit-expert",
      "auditor",
      "aurora-minimal",
      "automation-engineer",
      "awwwards-designer",
      "azuredevops-pro",
      "azuredevops-specialist",
      "azure-professional",
      "backendapi-specialist",
      "backend",
      "behance-designer",
      "behance-portfolio",
      "biomedical-engineer",
      "bitbucket-developer",
      "blockchain-dev",
      "blockchain-engineer",
      "blueprint-design",
      "boardroom-ready",
      "bold-headline",
      "bold-section-headers-universal",
      "bold-typography",
      "bold-typography-universal",
      "bootcamp-portfolio",
      "bootcamp-success-story",
      "border-frame-universal",
      "bordered-elegance",
      "brand-designer-template",
      "brand-identity",
      "brand-manager-strategic",
      "brand-manager",
      "brand-strategist",
      "branded-professional",
      "bright-graduate",
      "bronze-corporate",
      "budget-analyst",
      "burgundy-executive",
      "business-clean-layout",
      "business-clear-template",
      "business-development-manager",
      "business-elite",
      "business-graduate",
      "business-modern-grid",
      "business-modern",
      "business-sidebar-pro",
      "business-simple-modern",
      "bytecode-specialist",
      "ceo-profile",
      "cicd-pipeline-engineer",
      "cpa-professional",
      "c-suite-modern",
      "campus-influencer",
      "campus-leader",
      "canvas-artist",
      "capstone-showcase",
      "carbonmade-designer",
      "casestudy-designer",
      "catalyst-fresher",
      "certified-public-accountant",
      "charcoal-professional",
      "chemical-engineer-pro",
      "chevron-accent-universal",
      "chromatic-creative",
      "circular-elements-universal",
      "civil-engineerpe",
      "classic-serif-universal",
      "clean-basic-executive",
      "clean-corporate-simple",
      "clean-corporate",
      "clean-modern-universal",
      "clean-professional-simple",
      "clean-readable-pro",
      "clean-two-column-universal",
      "clinical-excellence",
      "clinical-minimal",
      "cloud-architect",
      "cloud-native",
      "cloud-solutions-architect",
      "cloudnative-architect",
      "clubhouse-moderator",
      "cobalt-professional",
      "code-craftsman",
      "code-minimal",
      "code-pinnacle",
      "code-snippet",
      "code-sphere",
      "code-vision",
      "codeforge-developer",
      "codepen-developer",
      "coding-bootcamp-grad",
      "coding-challenge-champion",
      "collage-art",
      "color-block-universal",
      "color-splash",
      "colorful-modern",
      "column-divide",
      "community-builder",
      "compact-elite-universal",
      "compact-professional",
      "compensation-benefits-manager",
      "compile-time-dev",
      "compliance-officer-legal",
      "compliance-officer",
      "componentui-designer",
      "composition-artist",
      "concept-creative",
      "conference-presenter",
      "connected-graduate",
      "connected-leader",
      "connected-professional",
      "construction-project-manager",
      "consultant",
      "containerops-engineer",
      "contemporary-split",
      "content-creator",
      "contract-specialist",
      "conversational-ux",
      "copywriter-creative",
      "coral-executive",
      "corner-accent-universal",
      "coroflot-portfolio",
      "corporate-apex",
      "corporate-attorney",
      "corporate-blue",
      "corporate-border-frame",
      "corporate-clean",
      "corporate-distinction",
      "corporate-easy-layout",
      "corporate-elite-plus",
      "corporate-elite",
      "corporate-excellence",
      "corporate-executive",
      "corporate-law",
      "corporate-legal-counsel",
      "corporate-minimalist-pro",
      "corporate-paradigm",
      "corporate-premier",
      "corporate-simple-template",
      "corporate-sovereign",
      "corporate-vanguard",
      "corporate-vision",
      "corporate-visionary",
      "cosmos-professional",
      "craft-artist",
      "creative-accent",
      "creative-canvas",
      "creative-crafted",
      "creative-director-elite",
      "creative-horizon",
      "creative-pulse",
      "creative-showcase-grid",
      "creative-timeline",
      "crimson-leadership",
      "crystal-executive",
      "curator-creative",
      "curriculum-developer",
      "customer-success-manager",
      "cyber-security",
      "cybersecurity-analyst",
      "dark-mode-dev",
      "data-engineer",
      "data-science",
      "data-scientist-pro",
      "dental-professional",
      "design-lead",
      "design-leader-portfolio",
      "design-maestro",
      "design-pinnacle",
      "design-school-grad",
      "design-sphere",
      "design-strategist",
      "design-systems-architect",
      "design-systems-portfolio",
      "designer-showcase",
      "designleadership-director",
      "designops-specialist",
      "designportfolio-specialist",
      "designstrategy-lead",
      "designsystem-architect",
      "designthinking-specialist",
      "dev-architecture",
      "dev-elite",
      "dev-momentum",
      "devops-automation",
      "devops-engineer",
      "devops-pro",
      "dev-prime",
      "devsecops-engineer",
      "developer-grid",
      "deviant-art-creator",
      "deviantart-artist",
      "devto-contributor",
      "diamond-accent-universal",
      "digital-artist-portfolio",
      "digital-artist",
      "digital-canvas",
      "digital-executive",
      "digital-graduate",
      "digital-identity",
      "digital-marketer",
      "digital-marketing-pro",
      "digital-marketing-specialist",
      "digital-native-grad",
      "digital-native-graduate",
      "digital-portfolio-grad",
      "digital-professional",
      "director-level",
      "diversity-inclusion-manager",
      "django-framework-pro",
      "django-fullstack",
      "docker-container-pro",
      "docker-specialist",
      "dockerhub-publisher",
      "dotnet-core-developer",
      "dotnet-developer",
      "dotted-grid-universal",
      "dribbble-creative",
      "dribbble-showcase",
      "dual-degree-graduate",
      "esl-teacher-certified",
      "eclipse-professional",
      "ecommerce-manager",
      "edgecompute-developer",
      "editorial-artist",
      "editorial-style",
      "educator-modern",
      "elasticsearch-dev",
      "elasticsearch-expert",
      "electrical-engineer",
      "elegant-professional",
      "elegant-serif",
      "elementary-teacher",
      "elevate-fresher",
      "elixir-developer",
      "email-marketing-specialist",
      "emerald-executive",
      "emerge-fresher",
      "employee-relations-specialist",
      "engineering-fresher",
      "engineering-manager",
      "enterprise-leader",
      "entrepreneurial-graduate",
      "entry-elite",
      "entry-horizon",
      "entry-sphere",
      "environmental-engineer",
      "equity-research-analyst",
      "estimator-cost-analyst",
      "event-planner-coordinator",
      "eventdriven-architect",
      "executive-ascendancy",
      "executive-authority",
      "executive-chef",
      "executive-clean-split",
      "executive-corner-accent",
      "executive-direct-layout",
      "executive-easy-template",
      "executive-impact",
      "executive-leadership",
      "executive-letterhead-universal",
      "executive-magnitude",
      "executive-minimal",
      "executive-nexus",
      "executive-pinnacle",
      "executive-plain-layout",
      "executive-prestige",
      "executive-sales-leader",
      "executive-signature",
      "executive-simple-clean",
      "executive-split-design",
      "executive",
      "executive-timeline-modern",
      "expression-artist",
      "faang-aspirant",
      "field-sales-specialist",
      "figma-designer-portfolio",
      "figma-expert",
      "finance-analyst",
      "finance-two-column",
      "financial-analystcfa",
      "financial-analyst",
      "financial-controller",
      "flutter-engineer",
      "flutter-mobile-dev",
      "flutterui-specialist",
      "flux-executive",
      "forensic-accountant",
      "forest-professional",
      "foundation-graduate",
      "framer-designer-portfolio",
      "framer-designer",
      "fresher-academic-style",
      "fresher-achievement",
      "fresher-bold-header",
      "fresher-box-shadow",
      "fresher-card-based",
      "fresher-centered-elegant",
      "fresher-circular-progress",
      "fresher-clean-modern",
      "fresher-color-accent",
      "fresher-compact-pro",
      "fresher-creative-edge",
      "fresher-dark-professional",
      "fresher-dash-border",
      "fresher-double-column",
      "fresher-elegant-sidebar",
      "fresher-elite",
      "fresher-executive-style",
      "fresher-geometric",
      "fresher-glassmorphism",
      "fresher-gradient-border",
      "fresher-iconography",
      "fresher-left-stripe",
      "fresher-lightweight",
      "fresher-minimal-grid",
      "fresher-minimalist-two-column",
      "fresher-modern-classic",
      "fresher-modern-split",
      "fresher-modern-tabs",
      "fresher-modern-two-column",
      "fresher-neon-accent",
      "fresher-polaroid-style",
      "fresher-professional-grid",
      "fresher-professional-minimal",
      "fresher-professional-sidebar",
      "fresher-progressive",
      "fresher-ribbon-style",
      "fresher-skills-first",
      "fresher-split-layout",
      "fresher-step-by-step",
      "fresher-tech-modern",
      "fresher-tech-split",
      "fresher",
      "fresher-timeline-dots",
      "fresher-timeline",
      "fresher-top-bottom",
      "fresher-two-tone",
      "fresher-wave-header",
      "freshers-crafted",
      "freshers-vision",
      "frontend-architect",
      "frontend",
      "full-stack-engineer",
      "full-stack-modern",
      "full-stack-pro",
      "fullstack-java-script",
      "fullstack",
      "gcparchitect",
      "gcp-cloud-engineer",
      "g-r-p-c-developer",
      "gallery-layout",
      "gen-z-graduate",
      "general-contractor",
      "genesis-graduate",
      "geometric-creative",
      "geometric-shapes-universal",
      "github-developer",
      "github-profile",
      "github-student-developer",
      "github-style",
      "gitflow-engineer",
      "github-portfolio-dev",
      "github-student",
      "gitlab-developer",
      "global-enterprise",
      "global-executive-pro",
      "global-leadership",
      "global-networker",
      "go-developer",
      "golang-backend-engineer",
      "gold-prestige",
      "gradient-header-universal",
      "graduate-innovator",
      "graduate-momentum",
      "graduate-prime",
      "graduate",
      "graduate-zenith",
      "graphql-architect",
      "graphql-developer",
      "graphdb-specialist",
      "graphic-design-pro",
      "growth-marketing-manager",
      "hr-analytics-manager",
      "hr-business-partner",
      "h-v-a-c-engineer",
      "hackathon-graduate",
      "hackathon-winner",
      "hackernews-developer",
      "hackerrank-expert",
      "harmony-executive",
      "headless-c-m-s-developer",
      "healthcare-administrator",
      "healthcare-professional",
      "healthcare-two-column",
      "hexagonal-pattern-universal",
      "high-school-teacher",
      "honors-student",
      "horizon-graduate",
      "hospitality-director",
      "hotel-manager-operations",
      "icon-bar-universal",
      "illustration-portfolio",
      "illustrator-artist",
      "imaginative-designer",
      "impression-designer",
      "in-vision-prototyper",
      "indigo-executive",
      "industrial-engineer",
      "infinity-loop-universal",
      "influencer-professional",
      "information-architect",
      "ink-brush",
      "inside-sales-representative",
      "instagram-creative",
      "instagram-influencer",
      "instructional-designer",
      "intellectual-property-attorney",
      "interaction-designer",
      "interactive-portfolio-designer",
      "interface-master",
      "internal-auditor",
      "internship-ready",
      "internship-showcase",
      "investment-banker",
      "jamstack-developer",
      "jade-professional",
      "java-developer",
      "java-enterprise-template",
      "jenkinscicd",
      "json-resume",
      "kafka-streaming-expert",
      "kafka-streaming",
      "kaggle-data-scientist",
      "keystone-graduate",
      "kotlin-android-dev",
      "kubernete-engineer",
      "kubernetes-specialist",
      "laravel-artisan",
      "launchpad-graduate",
      "lavender-executive",
      "layered-cards-universal",
      "lead-backend-engineer",
      "lead-frontend-engineer",
      "leadership-summit",
      "leadership-zenith",
      "learning-development-manager",
      "leetcode-champion",
      "legal-advisor",
      "legal-consultant",
      "legal-counsel",
      "legal-executive",
      "legal-operations-manager",
      "liberal-arts-graduate",
      "linkedin-ready-graduate",
      "linkedin-tech-pro",
      "linkedin-graduate",
      "linkedin-optimized",
      "linkedin-tech-expert",
      "litigation-attorney",
      "logistics-coordinator",
      "luxury-timeline",
      "ml-engineer",
      "machine-learning-engineer",
      "magazine-creative",
      "magazine-layout-universal",
      "manufacturing-engineer",
      "marketing-analytics-manager",
      "marketing-professional",
      "marketing-strategist",
      "marvel-app-designer",
      "masters-graduate",
      "mechanical-engineer-pro",
      "medical-assistant",
      "medical-certification",
      "medical-executive",
      "medical-professional",
      "medical-research",
      "medical-technologist",
      "medium-tech-writer",
      "medium-writer-creative",
      "medium-writer",
      "mental-health-counselor",
      "meridian-corporate",
      "microarch-engineer",
      "microinteraction-designer",
      "microservices-dev",
      "microservices-expert",
      "milestone-graduate",
      "minimal-chic",
      "minimal-corporate-pro",
      "minimal-direct-template",
      "minimal-elegance-universal",
      "minimal-lines-universal",
      "minimal-pro-layout",
      "minimal",
      "minimalist-modern-pro",
      "minimalist-pro-simple",
      "minimalist-pro",
      "mint-professional",
      "mlops-engineer",
      "mobile-dev",
      "mobile-developer",
      "mobile-first-designer",
      "modern-artist",
      "modern-business",
      "modern-clear-pro",
      "modern-corporate-grid",
      "modern-digital",
      "modern-educator-profession",
      "modern-minimalist-universal",
      "modern-plain-pro",
      "modern-professional-box",
      "modern-professional",
      "modern-simple-pro",
      "modern",
      "momentum-fresher",
      "mongodb-specialist",
      "monospace-tech",
      "motion-designer-portfolio",
      "motion-designer",
      "motion-graphics-artist",
      "motion-ui-designer",
      "multi-platform-artist",
      "multimedia-designer",
      "muse-creative",
      "narrative-creative",
      "navy-corporate",
      "neon-artist",
      "nestjs-backend",
      "networked-executive",
      "networked-graduate",
      "neural-engineer",
      "newspaper-style-universal",
      "nextjs-fullstack",
      "nextstep-fresher",
      "nexus-elite",
      "node-backend-specialist",
      "nodejs-developer",
      "npm-package-author",
      "nurse-specialist",
      "nursing-specialist",
      "nutritionist-dietitian",
      "observability-engineer",
      "obsidian-executive",
      "occupational-therapist",
      "online-course-instructor",
      "online-gallery-artist",
      "online-identity",
      "online-portfolio-fresher",
      "online-presence-fresher",
      "online-professional",
      "onyx-leadership",
      "open-source-contributor",
      "open-source",
      "opensource-developer",
      "operations-excellence",
      "operations-manager",
      "operations-two-column",
      "organizational-development",
      "p-m-executive",
      "palette-designer",
      "paralegal-certified",
      "paralegal",
      "parallax-style-universal",
      "paramedic-e-m-t",
      "pastel-creative",
      "pastry-chef",
      "pathway-graduate",
      "patreon-creative",
      "patreon-creator",
      "petroleum-engineer",
      "pewter-minimalist",
      "phd-candidate",
      "pharmacist-clinical",
      "photographer-pro",
      "photography-layout",
      "photography-pro-template",
      "physical-therapist",
      "physician-specialist",
      "pinnacle-elite",
      "pinterest-curator",
      "pinterest-designer",
      "pioneer-fresher",
      "pixelcraft-developer",
      "pixelperfect-designer",
      "platform-engineer",
      "platform-professional",
      "platinum-executive",
      "platinum-prestige",
      "plum-professional",
      "portfolio-artist",
      "portfolio-coder",
      "portfolio-first-graduate",
      "portfolio-graduate",
      "portfolio-manager",
      "portfolio-minimalist",
      "portfolio-professional",
      "portfolio-showcase",
      "portfolio-website-creative",
      "postgresqldba",
      "postgresql-expert",
      "potential-fresher",
      "premium-corporate-edge",
      "premium-elite",
      "premium-fresher",
      "premium-pro",
      "premium-universal",
      "principal-software-engineer",
      "principle-animator",
      "prism-professional",
      "private-tutor-specialist",
      "process-improvement",
      "procurement-specialist",
      "product-designer-pro",
      "product-designer-showcase",
      "product-designerux",
      "product-marketing-manager",
      "professional-accent-bar",
      "professional-basic-modern",
      "professional-classic",
      "professional-clean-simple",
      "professional-compact-universal",
      "professional-divider",
      "professional-easy-read",
      "professional-grid",
      "professional-header-banner",
      "professional-modern-edge",
      "professional-plain-simple",
      "professional-readable-layout",
      "professional-straightforward",
      "professional",
      "professional-timeline",
      "professional-vertical-line",
      "profile-centric",
      "profile-driven-grad",
      "project-managerpmp",
      "project-manager-pro",
      "project-showcase-grad",
      "property-manager-commercial",
      "protfolio-showcase-ux",
      "prototype-specialist",
      "py-torch-developer",
      "pypi-contributor",
      "python-developer-pro",
      "python-developer",
      "pythonml-engineer",
      "qa-automation-engineer",
      "quality-assurance-engineer",
      "quantum-coder",
      "quantum-professional",
      "rabbit-m-q-specialist",
      "radiance-corporate",
      "radiology-technician",
      "rails-developer",
      "react-developer",
      "react-frontend-pro",
      "react-native-dev",
      "react-native-developer",
      "react-native-expert",
      "real-estate-appraiser",
      "real-estate-broker",
      "redis-cache-specialist",
      "redis-engineer",
      "refined",
      "registered-nurse-pro",
      "remote-work-ready",
      "research-graduate",
      "research-publication-grad",
      "responsive-ux",
      "restaurant-manager",
      "retro-professional-universal",
      "risk-management-analyst",
      "robotics-engineer",
      "rose-professional",
      "rounded-corners-universal",
      "ruby-corporate",
      "rust-developer-pro",
      "rust-systems-engineer",
      "s-e-o-specialist-pro",
      "stem-graduate",
      "sales-achievement",
      "sales-executive-pro",
      "sales-executive",
      "sales-manager",
      "sales-marketing-hybrid",
      "sapphire-executive",
      "sapphire-professional",
      "scala-backend-engineer",
      "scala-engineer",
      "scholarship-graduate",
      "security-engineer",
      "senior-backend",
      "seniordevops-engineer",
      "seniordotnet-developer",
      "senior-executive-pro",
      "senior-frontend",
      "senior-full-stack-developer",
      "senior-java-developer",
      "senior-mobile-engineer",
      "senior",
      "serenity-minimal",
      "serverless-developer",
      "serverless-specialist",
      "service-designer",
      "servicedesign-specialist",
      "sidebar-accent",
      "simple-business-clean",
      "simple-clear-business",
      "simple-executive-layout",
      "simple-modern-executive",
      "simple-professional-clean",
      "simple-structured-template",
      "site-reliability-engineer",
      "sketch-expert-portfolio",
      "sketch-specialist",
      "sky-modern",
      "slate-minimalist",
      "social-creative-influencer",
      "social-executive",
      "social-first-fresher",
      "social-graduate",
      "social-media-creative",
      "social-media-pro",
      "social-media-savvy-grad",
      "social-savvy",
      "software-craftsman",
      "software-master",
      "software",
      "software-vision",
      "solidity-developer",
      "solutions-architect",
      "sommelier-wine-specialist",
      "sound-cloud-producer",
      "soundcloud-artist",
      "spark-fresher",
      "special-education-teacher",
      "spectrum-professional",
      "speech-pathologist",
      "split-pane-universal",
      "spotify-artist",
      "spotify-musician",
      "spotlight-header-universal",
      "spring-boot-developer",
      "stack-overflow-inspired",
      "stacked-sections-universal",
      "stackmaster-fullstack",
      "stackoverflow-dev",
      "staff-engineer",
      "starter",
      "startup-intern",
      "steel-professional",
      "sterling-executive",
      "strategic-executive-plus",
      "strategic-leader",
      "strategic-leadership",
      "striped-background-universal",
      "structural-engineer",
      "student-athlete",
      "student-developer-portfolio",
      "student-educator",
      "student-engagement",
      "studio-artist",
      "study-abroad-graduate",
      "substack-author",
      "substack-writer",
      "supply-chain-manager",
      "svelte-developer",
      "swift-i-o-s-developer",
      "swiss-style-universal",
      "system-architect",
      "talent-acquisition-specialist",
      "tangerine-modern",
      "tax-specialist-pro",
      "tax-specialist",
      "teacher-professional",
      "teaching-certified",
      "teaching-excellence",
      "teal-modern",
      "tech-blogger-dev",
      "tech-blogger-graduate",
      "tech-crafted",
      "tech-grid",
      "tech-horizon",
      "tech-lead",
      "tech-pioneer",
      "tech-savvy-fresher",
      "tech-stack-pro",
      "tech-vanguard",
      "tensor-flowml-engineer",
      "terminal-console",
      "terminal-theme",
      "terraformdevops",
      "thin-border-universal",
      "three-d-modeling-artist",
      "tiktok-creator",
      "tiktok-content-creator",
      "titan-corporate",
      "top-bar-universal",
      "treasury-analyst",
      "triangular-elements-universal",
      "twitch-streamer-creative",
      "twitch-streamer",
      "twitter-dev",
      "two-tone-classic",
      "two-tone-split-universal",
      "type-script-expert",
      "typewriter-style",
      "typographer-specialist",
      "ui-specialist",
      "uiux-designer-pro",
      "ux-researcher",
      "uiux-portfolio-pro",
      "unity-game-developer",
      "university-professor",
      "urban-designer",
      "userflow-designer",
      "userresearch-specialist",
      "ux-researcher-portfolio",
      "uxfolio-designer",
      "vp-executive",
      "velocity-executive",
      "venture-fresher",
      "vertex-professional",
      "veterinary-doctor",
      "vibrant-designer",
      "video-editor-creative",
      "video-producer",
      "vimeo-videographer",
      "vintage-poster",
      "violet-corporate",
      "vision-designer",
      "visionary-creative",
      "visual-designer-pro",
      "visual-designer-showcase",
      "visual-storyteller-template",
      "volunteer-leader",
      "vuejs-developer",
      "vue-master",
      "vue-specialist",
      "watermark-style-universal",
      "wave-pattern-universal",
      "web-assembly-engineer",
      "web-designer-modern",
      "web-portfolio-grad",
      "webflow-designer-portfolio",
      "webflow-developer",
      "webpresence-executive",
      "webrtc-engineer",
      "wide-margin-universal",
      "wireframe-specialist",
      "youtube-educator",
      "youtube-creator",
      "youtube-dev-educator",
      "zenith-corporate",
      "zeplin-handoff-specialist",
      "zigzag-border-universal",
      "ios-swift-engineer",
    ],
  },
  {
    id: "universal-professional",
    name: "Universal Professional",
    description: "Versatile templates suitable for all industries and roles",
    icon: Star,
    color: "#f59e0b",
    gradientFrom: "#f59e0b",
    gradientTo: "#d97706",
    templateIds: [
      "professional",
      "minimal",
      "premium-universal",
      "premium-pro",
      "refined",
      "premium-elite",
      "bold-headline",
      "contemporary-split",
      // New Universal Professional Templates
      "corporate-blue",
      "minimalist-pro",
      "business-modern",
      "professional-timeline",
      "clean-corporate",
      "modern-professional",
      "elegant-professional",
      "professional-grid",
      "business-elite",
      "corporate-clean",
      "professional-classic",
      "modern-business",
      // New Universal Templates
      "executive-minimal",
      "sidebar-accent",
      "two-tone-classic",
      "bordered-elegance",
      "column-divide",
      "compact-professional",
      // New 2024 Universal Templates
      // 2025 New Universal Profile Templates
      "swiss-style-universal",
      "executive-letterhead-universal",
      "border-frame-universal",
      // 2025 Second Batch Universal Profile Templates
      "gradient-header-universal",
    ],
  },
  {
    id: "fresh-graduates",
    name: "Fresh Graduates & Students",
    description: "Entry-level templates for recent graduates and students",
    icon: GraduationCap,
    color: "#10b981",
    gradientFrom: "#10b981",
    gradientTo: "#059669",
    templateIds: [
      "graduate",
      "starter",
      "fresher",
      "premium-fresher",
      "fresher-elite",
      "fresher-minimal-grid",
      "fresher-dark-professional",
      "fresher-color-accent",
      "fresher-timeline",
      "fresher-skills-first",
      "fresher-card-based",
      "fresher-two-tone",
      "fresher-centered-elegant",
      "fresher-geometric",
      "fresher-achievement",
      "fresher-modern-two-column",
      "fresher-professional-sidebar",
      "fresher-clean-modern",
      "fresher-tech-split",
      "fresher-executive-style",
      "fresher-bold-header",
      "fresher-minimalist-two-column",
      "fresher-creative-edge",
      "fresher-professional-grid",
      "fresher-modern-classic",
      "fresher-split-layout",
      "fresher-compact-pro",
      "fresher-elegant-sidebar",
      "fresher-tech-modern",
      "fresher-professional-minimal",
      "academic-achiever",
      "graduate-innovator",
      "campus-leader",
      "scholarship-graduate",
      "honors-student",
      "stem-graduate",
      "internship-ready",
      "research-graduate",
      "entrepreneurial-graduate",
      "volunteer-leader",
      "coding-bootcamp-grad",
      "liberal-arts-graduate",
      "business-graduate",
      "engineering-fresher",
      "design-school-grad",
      "masters-graduate",
      "phd-candidate",
      "student-athlete",
      "study-abroad-graduate",
      "dual-degree-graduate",
      "digital-native-graduate",
      "tech-savvy-fresher",
      "linkedin-ready-graduate",
      "github-student-developer",
      "portfolio-first-graduate",
      "connected-graduate",
      "social-media-savvy-grad",
      "open-source-contributor",
      "hackathon-winner",
      "coding-challenge-champion",
      "capstone-showcase",
      "research-publication-grad",
      "conference-presenter",
      "startup-intern",
      "faang-aspirant",
      "bootcamp-success-story",
      "remote-work-ready",
      "community-builder",
      "tech-blogger-graduate",
      "youtube-educator",
      "academic-scholar",
      "student-educator",
      "github-style",
      "github-developer",
      "linkedin-tech-pro",
      "social-media-creative",
      "artistic-horizon",
      "artistic-momentum",
      "academic-advisor",
      "design-systems-architect",
      "equity-research-analyst",
      "executive-ascendancy",
      "online-course-instructor",
      "portfolio-artist",
      "portfolio-manager",
      "rust-systems-engineer",
      "ux-researcher",
    ],
  },
  {
    id: "software-technology",
    name: "Software & Technology",
    description: "Resume templates for developers, engineers, and tech professionals",
    icon: Code,
    color: "#3b82f6",
    gradientFrom: "#3b82f6",
    gradientTo: "#2563eb",
    templateIds: [
      "frontend",
      "backend",
      "fullstack",
      "senior",
      "senior-frontend",
      "senior-backend",
      "software",
      "tech-grid",
      // New Software Development Templates
      "java-developer",
      "dotnet-developer",
      "devops-engineer",
      "cloud-architect",
      "mobile-developer",
      "react-native-developer",
      "data-engineer",
      "machine-learning-engineer",
      "qa-automation-engineer",
      "security-engineer",
      "python-developer",
      "nodejs-developer",
      "react-developer",
      "go-developer",
      "kubernetes-engineer",
      // Senior/Lead Software Engineering Templates
      "senior-java-developer",
      "senior-dotnet-developer",
      "senior-devops-engineer",
      "lead-backend-engineer",
      "lead-frontend-engineer",
      "senior-fullstack-developer",
      "principal-software-engineer",
      "staff-engineer",
      "engineering-manager",
      "solutions-architect",
      "senior-mobile-engineer",
      "platform-engineer",
      "site-reliability-engineer",
      "backend-api-specialist",
      "frontend-architect",
      // New Software Engineering Templates
      "code-minimal",
      "tech-stack-pro",
      "github-style",
      "developer-grid",
      "terminal-theme",
      "algo-engineer",
      "fullstack-modern",
      "devops-pro",
      "ml-engineer",
      // New 2024 Tech Templates
      "code-craftsman",
      "tech-pioneer",
      "dev-architecture",
      "software-master",
      "tech-vanguard",
      "code-sphere",
      "dev-elite",
      "tech-horizon",
      "software-craftsman",
      "code-vision",
      "dev-prime",
      "tech-crafted",
      "software-vision",
      "code-pinnacle",
      "dev-momentum",
      // 2025 New Software/Tech Templates
      "dark-mode-dev",
      "code-snippet",
      "api-doc",
      "stackoverflow-inspired",
      "github-profile",
      "terminal-console",
      "json-resume",
      "monospace-tech",
      "blueprint-design",
      "system-architect",
      "cloud-native",
      "microservices-dev",
      "agile-scrum",
      "tech-lead",
      "open-source",
      "fullstack-pro",
      "data-science",
      "cyber-security",
      "blockchain-dev",
      "ai-engineer",
      "mobile-dev",
      // 2025 New Software/Tech Templates (Batch 3)
      "react-frontend-pro",
      "node-backend-specialist",
      "fullstack-engineer",
      "python-developer-pro",
      "java-enterprise-template",
      "devops-automation",
      "cloud-solutions-architect",
      "microservices-expert",
      "kubernetes-specialist",
      "docker-container-pro",
      "graphql-developer",
      "typescript-expert",
      "vuejs-developer",
      "angular-specialist",
      "springboot-developer",
      "django-framework-pro",
      "aws-cloud-engineer",
      "azure-devops-specialist",
      "gcp-architect",
      "serverless-developer",
      // 2025 New Software/Tech Templates (Batch 4)
      "rust-developer-pro",
      "scala-engineer",
      "elixir-developer",
      "swift-ios-developer",
      "kotlin-android-dev",
      "flutter-mobile-dev",
      "react-native-expert",
      "tensorflow-ml-engineer",
      "pytorch-developer",
      "mongodb-specialist",
      "postgresql-expert",
      "redis-cache-specialist",
      "elasticsearch-dev",
      "kafka-streaming-expert",
      "cicd-pipeline-engineer",
      // 2025 New Software Templates (25 templates)
      "vue-specialist",
      "svelte-developer",
      "flutter-engineer",
      "swift-ios-developer",
      "rust-systems-engineer",
      "scala-backend-engineer",
      "elixir-developer",
      "graphql-architect",
      "typescript-expert",
      "nextjs-fullstack",
      "nestjs-backend",
      "django-fullstack",
      "spring-boot-developer",
      "postgresql-dba",
      "mongodb-specialist",
      "redis-engineer",
      "elasticsearch-expert",
      "terraform-devops",
      "ansible-automation",
      "jenkins-cicd",
      "kafka-streaming",
      "rabbitmq-specialist",
      "grpc-developer",
      "webassembly-engineer",
      "unity-game-developer",
      // 2025 Batch 2 - New Software/Tech Templates (25 templates)
      "github-developer",
      "linkedin-tech-pro",
      "laravel-artisan",
      "rails-developer",
      "angular-specialist",
      "vue-master",
      "kotlin-android-dev",
      "ios-swift-engineer",
      "docker-specialist",
      "aws-solutions-architect",
      "gcp-cloud-engineer",
      "azure-devops-pro",
      "react-native-dev",
      "flutter-ui-specialist",
      "dotnet-core-developer",
      "golang-backend-engineer",
      "python-ml-engineer",
      "data-scientist-pro",
      "blockchain-engineer",
      "solidity-developer",
      "cybersecurity-analyst",
      "devsecops-engineer",
      "fullstack-javascript",
      "jamstack-developer",
      "headless-cms-developer",
      // 2025 Batch 4 - New Software/Tech Templates (20 templates)
      "codeforge-developer",
      "quantum-coder",
      "neural-engineer",
      "pixelcraft-developer",
      "cloudnative-architect",
      "bytecode-specialist",
      "agileflow-developer",
      "stackmaster-fullstack",
      "gitflow-engineer",
      "compile-time-dev",
      "microarch-engineer",
      "serverless-specialist",
      "edgecompute-developer",
      "webrtc-engineer",
      "graphdb-specialist",
      "containerops-engineer",
      "apigateway-architect",
      "observability-engineer",
      "eventdriven-architect",
      "mlops-engineer",
      // 2025 Batch 5 - Social Links Templates
      "github-portfolio-dev",
      "opensource-developer",
      "stackoverflow-dev",
      "codepen-developer",
      "portfolio-coder",
      "tech-blogger-dev",
      "youtube-dev-educator",
      "linkedin-tech-expert",
      "twitter-dev",
      "medium-tech-writer",
      "devto-contributor",
      "hackernews-developer",
      "gitlab-developer",
      "bitbucket-developer",
      "npm-package-author",
      "pypi-contributor",
      "dockerhub-publisher",
      "kaggle-data-scientist",
      "leetcode-champion",
      "hackerrank-expert",
    ],
  },
  {
    id: "creative-design",
    name: "Creative & Design",
    description: "Modern creative templates for designers and creative professionals",
    icon: Palette,
    color: "#ec4899",
    gradientFrom: "#ec4899",
    gradientTo: "#db2777",
    templateIds: [
      "creative-accent",
      "modern",
      "elegant-serif",
      // New Creative Templates
      "artistic-bold",
      "designer-showcase",
      "creative-timeline",
      "colorful-modern",
      "asymmetric-creative",
      // New 2024 Creative Templates
      "creative-canvas",
      "design-maestro",
      "artistic-vision",
      "creative-pulse",
      "design-pinnacle",
      "artistic-horizon",
      "creative-crafted",
      "design-sphere",
      "artistic-momentum",
      "creative-horizon",
      // 2025 New Creative Templates
      "magazine-creative",
      "portfolio-showcase",
      "artistic-grid",
      "bold-typography",
      "color-splash",
      "minimal-chic",
      "photography-layout",
      "brand-identity",
      "vintage-poster",
      "modern-artist",
      "gallery-layout",
      "editorial-style",
      "urban-designer",
      "pastel-creative",
      "neon-artist",
      "geometric-creative",
      "typewriter-style",
      "ink-brush",
      "collage-art",
      "digital-canvas",
      // 2025 New Creative/Design Templates (Batch 2)
      "portfolio-minimalist",
      "creative-showcase-grid",
      "art-director-modern",
      "uiux-designer-pro",
      "graphic-design-pro",
      "brand-designer-template",
      "motion-graphics-artist",
      "illustration-portfolio",
      "photography-pro-template",
      "video-editor-creative",
      "threed-modeling-artist",
      "web-designer-modern",
      "product-designer-ux",
      "interaction-designer",
      "visual-storyteller-template",
      // 2025 New Creative & Design Templates (25 templates)
      "portfolio-artist",
      "motion-designer",
      "brand-strategist",
      "content-creator",
      "illustrator-artist",
      "video-producer",
      "copywriter-creative",
      "art-director-pro",
      "photographer-pro",
      "typographer-specialist",
      "digital-artist",
      "creative-director-elite",
      "social-media-creative",
      "animation-artist",
      "multimedia-designer",
      "ux-researcher",
      "ui-specialist",
      "product-designer-pro",
      "interaction-designer",
      "service-designer",
      "design-systems-architect",
      "accessibility-designer",
      "design-lead",
      "design-strategist",
      "visual-designer-pro",
      // 2025 Batch 2 - New Creative Templates (15 templates)
      "behance-designer",
      "dribbble-creative",
      "instagram-influencer",
      "pinterest-curator",
      "vimeo-videographer",
      "medium-writer",
      "tiktok-creator",
      "twitch-streamer",
      "soundcloud-producer",
      "spotify-artist",
      "artstation-artist",
      "deviantart-creator",
      "patreon-creator",
      "substack-writer",
      "clubhouse-moderator",
      // 2025 Batch 2 - New Design Templates (10 templates)
      "figma-expert",
      "sketch-specialist",
      "adobe-xd-designer",
      "framer-designer",
      "webflow-developer",
      "principle-animator",
      "invision-prototyper",
      "marvel-app-designer",
      "zeplin-handoff-specialist",
      "abstract-version-designer",
      // 2025 Batch 4 - New Creative & Design Templates (40 templates)
      "muse-creative",
      "canvas-artist",
      "palette-designer",
      "visionary-creative",
      "studio-artist",
      "creative-pulse",
      "artisan-designer",
      "chromatic-creative",
      "expression-artist",
      "imaginative-designer",
      "aesthetic-creative",
      "composition-artist",
      "impression-designer",
      "narrative-creative",
      "craft-artist",
      "vibrant-designer",
      "concept-creative",
      "editorial-artist",
      "vision-designer",
      "curator-creative",
      "interface-master",
      "designsystem-architect",
      "userflow-designer",
      "prototype-specialist",
      "pixelperfect-designer",
      "responsive-ux",
      "wireframe-specialist",
      "microinteraction-designer",
      "accessibility-ux",
      "userresearch-specialist",
      "information-architect",
      "designthinking-specialist",
      "componentui-designer",
      "designops-specialist",
      "mobile-first-designer",
      "servicedesign-specialist",
      "designstrategy-lead",
      "conversational-ux",
      "motion-ui-designer",
      "designleadership-director",
      // 2025 Batch 5 - Social Links Templates
      "behance-portfolio",
      "dribbble-showcase",
      "artstation-pro",
      "instagram-creative",
      "pinterest-designer",
      "youtube-creator",
      "tiktok-content-creator",
      "vimeo-videographer",
      "soundcloud-artist",
      "spotify-musician",
      "twitch-streamer-creative",
      "deviantart-artist",
      "patreon-creative",
      "medium-writer-creative",
      "substack-author",
      "portfolio-website-creative",
      "online-gallery-artist",
      "social-creative-influencer",
      "multi-platform-artist",
      "digital-artist-portfolio",
      "figma-designer-portfolio",
      "adobe-portfolio-designer",
      "sketch-expert-portfolio",
      "webflow-designer-portfolio",
      "framer-designer-portfolio",
      "uxfolio-designer",
      "coroflot-portfolio",
      "carbonmade-designer",
      "awwwards-designer",
      "uiux-portfolio-pro",
      "designportfolio-specialist",
      "casestudy-designer",
      "protfolio-showcase-ux",
      "interactive-portfolio-designer",
      "ux-researcher-portfolio",
      "product-designer-showcase",
      "design-systems-portfolio",
      "motion-designer-portfolio",
      "visual-designer-showcase",
      "design-leader-portfolio",
    ],
  },
  {
    id: "business-leadership",
    name: "Business & Leadership",
    description: "Executive and leadership templates for senior professionals",
    icon: Briefcase,
    color: "#8b5cf6",
    gradientFrom: "#8b5cf6",
    gradientTo: "#7c3aed",
    templateIds: [
      "executive",
      "sapphire-executive",
      "luxury-timeline",
      "corporate-executive",
      "analyst",
      // 2025 New Business Leadership Templates
      "executive-leadership",
      "ceo-profile",
      "strategic-leader",
      "director-level",
      "vp-executive",
    ],
  },
  {
    id: "healthcare-medical",
    name: "Healthcare & Medical",
    description: "Professional templates for healthcare and medical professionals",
    icon: Heart,
    color: "#ef4444",
    gradientFrom: "#ef4444",
    gradientTo: "#dc2626",
    templateIds: [
      "medical-professional",
      "healthcare-two-column",
      "nurse-specialist",
      "medical-executive",
      "clinical-minimal",
      // 2025 New Healthcare Templates
      "medical-certification",
      "clinical-excellence",
      "healthcare-professional",
      "nursing-specialist",
      "medical-research",
      // 2025 Batch 3 - Healthcare & Medical Professionals (15 templates)
      "registered-nurse-pro",
      "physician-specialist",
      "dental-professional",
      "pharmacist-clinical",
      "physical-therapist",
      "medical-technologist",
      "radiology-technician",
      "healthcare-administrator",
      "mental-health-counselor",
      "occupational-therapist",
      "speech-pathologist",
      "veterinary-doctor",
      "nutritionist-dietitian",
      "medical-assistant",
      "paramedic-emt",
    ],
  },
  {
    id: "education-teaching",
    name: "Education & Teaching",
    description: "Templates designed for educators and academic professionals",
    icon: BookOpen,
    color: "#06b6d4",
    gradientFrom: "#06b6d4",
    gradientTo: "#0891b2",
    templateIds: [
      "teacher-professional",
      "academic-scholar",
      "educator-modern",
      "teaching-certified",
      "student-educator",
      // 2025 New Education Templates
      "teaching-excellence",
      "modern-educator-profession",
      "academic-educator",
      "curriculum-developer",
      "student-engagement",
      // 2025 Batch 3 - Education & Teaching Professionals (10 templates)
      "university-professor",
      "elementary-teacher",
      "high-school-teacher",
      "special-education-teacher",
      "esl-teacher-certified",
      "curriculum-developer",
      "instructional-designer",
      "academic-advisor",
      "online-course-instructor",
      "private-tutor-specialist",
    ],
  },
  {
    id: "finance-accounting",
    name: "Finance & Accounting",
    description: "Professional templates for finance and accounting experts",
    icon: DollarSign,
    color: "#84cc16",
    gradientFrom: "#84cc16",
    gradientTo: "#65a30d",
    templateIds: [
      "cpa-professional",
      "finance-analyst",
      "accounting-executive",
      "auditor",
      "finance-two-column",
      // 2025 New Finance Templates
      "financial-analyst",
      "accounting-pro",
      "investment-banker",
      "tax-specialist",
      "audit-expert",
      // 2025 Batch 3 - Finance & Accounting Professionals (12 templates)
      "financial-analyst-cfa",
      "investment-banker",
      "certified-public-accountant",
      "tax-specialist-pro",
      "financial-controller",
      "portfolio-manager",
      "risk-management-analyst",
      "treasury-analyst",
      "forensic-accountant",
      "internal-auditor",
      "budget-analyst",
      "equity-research-analyst",
    ],
  },
  {
    id: "sales-marketing",
    name: "Sales & Marketing",
    description: "Dynamic templates for sales and marketing professionals",
    icon: TrendingUp,
    color: "#f97316",
    gradientFrom: "#f97316",
    gradientTo: "#ea580c",
    templateIds: [
      "sales-executive",
      "marketing-professional",
      "sales-marketing-hybrid",
      "digital-marketer",
      "sales-manager",
      // 2025 New Sales & Marketing Templates
      "sales-achievement",
      "marketing-strategist",
      "digital-marketing-pro",
      "brand-manager",
      "executive-sales-leader",
      // 2025 Batch 3 - Sales & Marketing Professionals (15 templates)
      "sales-executive-pro",
      "account-manager-enterprise",
      "digital-marketing-specialist",
      "brand-manager-strategic",
      "seo-specialist-pro",
      "growth-marketing-manager",
      "email-marketing-specialist",
      "product-marketing-manager",
      "business-development-manager",
      "inside-sales-representative",
      "field-sales-specialist",
      "customer-success-manager",
      "marketing-analytics-manager",
      "ecommerce-manager",
      "affiliate-marketing-manager",
    ],
  },
  {
    id: "legal-consulting",
    name: "Legal & Consulting",
    description: "Refined templates for legal and consulting professionals",
    icon: Scale,
    color: "#6366f1",
    gradientFrom: "#6366f1",
    gradientTo: "#4f46e5",
    templateIds: [
      "attorney-professional",
      "legal-counsel",
      "consultant",
      "legal-executive",
      "paralegal",
      // 2025 New Legal Templates
      "corporate-legal-counsel",
      "corporate-law",
      "litigation-attorney",
      "compliance-officer",
      "legal-advisor",
      // 2025 Batch 3 - Legal Professionals (8 templates)
      "corporate-attorney",
      "litigation-attorney",
      "paralegal-certified",
      "legal-consultant",
      "compliance-officer-legal",
      "contract-specialist",
      "intellectual-property-attorney",
      "legal-operations-manager",
    ],
  },
  {
    id: "operations-management",
    name: "Operations & Project Management",
    description: "Strategic templates for operations and project managers",
    icon: Settings,
    color: "#14b8a6",
    gradientFrom: "#14b8a6",
    gradientTo: "#0d9488",
    templateIds: [
      "project-manager-pmp",
      "operations-manager",
      "pm-executive",
      "agile-scrum",
      "operations-two-column",
      // 2025 New Operations Templates
      "project-manager-pro",
      "operations-excellence",
      "process-improvement",
      "supply-chain-manager",
      "agile-project-lead",
      // 2025 Batch 3 - Operations & Logistics (3 templates)
      "supply-chain-manager",
      "logistics-coordinator",
      "procurement-specialist",
    ],
  },
  {
    id: "engineering",
    name: "Engineering",
    description: "Professional templates for engineering and technical professionals",
    icon: Wrench,
    color: "#475569",
    gradientFrom: "#475569",
    gradientTo: "#334155",
    templateIds: [
      // 2025 Batch 3 - Engineering Professionals (15 templates)
      "mechanical-engineer-pro",
      "civil-engineer-pe",
      "electrical-engineer",
      "chemical-engineer-pro",
      "aerospace-engineer",
      "biomedical-engineer",
      "industrial-engineer",
      "environmental-engineer",
      "petroleum-engineer",
      "structural-engineer",
      "manufacturing-engineer",
      "quality-assurance-engineer",
      "automation-engineer",
      "robotics-engineer",
      "hvac-engineer",
    ],
  },
  {
    id: "human-resources",
    name: "Human Resources",
    description: "HR and people operations templates for talent management professionals",
    icon: Users,
    color: "#be185d",
    gradientFrom: "#be185d",
    gradientTo: "#9f1239",
    templateIds: [
      // 2025 Batch 3 - Human Resources Professionals (8 templates)
      "hr-business-partner",
      "talent-acquisition-specialist",
      "compensation-benefits-manager",
      "learning-development-manager",
      "employee-relations-specialist",
      "hr-analytics-manager",
      "organizational-development",
      "diversity-inclusion-manager",
    ],
  },
  {
    id: "hospitality-culinary",
    name: "Hospitality & Culinary",
    description: "Templates for hospitality, culinary, and event management professionals",
    icon: Utensils,
    color: "#92400e",
    gradientFrom: "#92400e",
    gradientTo: "#78350f",
    templateIds: [
      // 2025 Batch 3 - Hospitality & Culinary Professionals (7 templates)
      "executive-chef",
      "hotel-manager-operations",
      "restaurant-manager",
      "event-planner-coordinator",
      "sommelier-wine-specialist",
      "pastry-chef",
      "hospitality-director",
    ],
  },
  {
    id: "real-estate-construction",
    name: "Real Estate & Construction",
    description: "Templates for real estate, property management, and construction professionals",
    icon: Home,
    color: "#15803d",
    gradientFrom: "#15803d",
    gradientTo: "#166534",
    templateIds: [
      // 2025 Batch 3 - Real Estate & Construction Professionals (7 templates)
      "real-estate-broker",
      "property-manager-commercial",
      "construction-project-manager",
      "architect-registered",
      "general-contractor",
      "estimator-cost-analyst",
      "real-estate-appraiser",
    ],
  },
];

// Helper function to get category by id
export const getCategoryById = (id: string): ProfessionCategory | undefined => {
  return professionCategories.find((cat) => cat.id === id);
};

// Helper function to get templates for a category
export const getTemplatesForCategory = (categoryId: string): string[] => {
  const category = getCategoryById(categoryId);
  return category?.templateIds || [];
};
