# =============================================================================
# Google Cloud Build Configuration
# =============================================================================
# This file configures automatic deployment to Cloud Run when pushing to GitHub.
#
# Setup:
# 1. Connect your GitHub repo in Cloud Build
# 2. Set trigger to run on push to main branch
# 3. Set substitution variables for secrets
# =============================================================================

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/resumecook-api:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/resumecook-api:latest'
      - './cloud-run'

  # Step 2: Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/resumecook-api:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/resumecook-api:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'resumecook-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/resumecook-api:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '120s'
      - '--concurrency'
      - '80'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production'

images:
  - 'gcr.io/$PROJECT_ID/resumecook-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/resumecook-api:latest'

# Build timeout (10 minutes should be plenty)
timeout: '600s'

# Substitution variables (set in Cloud Build trigger)
substitutions:
  _REGION: 'us-central1'
